print("One fine summer day")
print("A camel came to the oasis")
print("He was very thirsty")
print("So he drank a lot of water")
print("And then he fell asleep")
print("When he woke up, the sun was setting")
print("And the camel was very hungry")
print("So he ate a lot of food")
print("And then he went to bed")
print("The next morning, the camel woke up")
print("And he felt very good")
print("So he set off on his journey")
print("And he traveled for many days")
print("Until he reached his destination")
print("The camel was very happy")
print("Because he had finished his journey")
print("And he was home")