print(" Hello to all ")
print(" Welcome to the world of Git ")
print(" Git is a distributed version control system ")
print(" It is used to track changes to a set of files ")
print(" It allows developers to collaborate on projects ")
print(" Git is free and open source ")
print(" It is used by many large companies, such as Google, Facebook, and Amazon ")
print(" Git is a powerful tool that can be used to improve the efficiency and quality of software development ")
print(" I hope you enjoy learning about Git ")
print(" Thank you for your time ")